# Generated by Django 4.2.4 on 2023-08-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('profesor', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='entregables',
            old_name='fecha_entrega',
            new_name='fecha',
        ),
    ]
