# Generated by Django 4.2.4 on 2023-08-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_sedes_delete_tutores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedes',
            name='telefono',
            field=models.IntegerField(),
        ),
    ]
